server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account?useInformationSchema=false
    username: root
    password: root

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connect-timeout: 300000
        read-timeout: 300000

logging:
  level:
    io:
      seata: info


mybatis:
  mapperLocations: classpath:mapper/*.xml

